'use strict';
//15/03/23

// Font Awesome
// https://www.fontawesomecheatsheet.com/
const chars = {
	// Web
	lastFm			: '\uf202',
	link			: '\uf0c1',
	// Standard
	close 			: '\uf00D',
	ratingOn 		: '\uf005',
	ratingOff		: '\uf006',
	heartOn			: '\uf004',
	heartOff		: '\uf08A',
	music			: '\uf001',
	headphones 		: '\uf025',
	speaker 		: '\uf028',
	microphone 		: '\uf130',
	noMicrophone 	: '\uf131',
	minus			: '\uf068',
	plus			: '\uf067',
	wand			: '\uf0d0',
	wrench			: '\uf0ad',
	cogs			: '\uf085',
	calendar		: '\uf073',
	bolt			: '\uf0e7',
	dotCircle		: '\uf192',
	hourglassStart	: '\uf251',
	hourglassHalf	: '\uf252',
	hourglassEnd	: '\uf253',
	hourglass		: '\uf254',
	hourglassAlt	: '\uf250',
	lock			: '\uf023',
	unlock			: '\uf09c',
	unlockAlt		: '\uf13e',
	cut				: '\uf0c4',
	sitemap			: '\uf0e8',
	close			: '\uf00d',
	closeAlt		: '\uf2d4',
	expand			: '\uf065',
	exchange		: '\uf0ec',
	ban 			: '\uf05e',
	recycle			: '\uf1b8',
	puzzle			: '\uf12e',
	moon			: '\uf186',
	lighbulb		: '\uf0eb',
	// Files
	folderOpenBlack	: '\uf07c',
	folderOpenWhite	: '\uf115',
	emptyFileWhite	: '\uf016',
	emptyFilesWhite	: '\uf0c5',
	fileWhite		: '\uf0f6',
	emptyFileBlack	: '\uf15b',
	fileBlack		: '\uf15c',
	save 			: '\uf0c7',
	fileCode		: '\uf1c9',
	fileSound		: '\uf1c7',
	// Utilities
	search			: '\uf002',
	menu			: '\uf0C9',
	console			: '\uf120',
	preferences 	: '\uf013',
	searchPlus 		: '\uf00e',
	searchMinus		: '\uf010',
	tag				: '\uf02b',
	tags 			: '\uf02c',
	duplicates 		: '\uf0c5',
	filter 			: '\uf0b0',
	info 			: '\uf05A',
	question		: '\uf29c',
	tasks 			: '\uf0cb',
	history			: '\uf1da',
	bookmark		: '\uf02e',
	send			: '\uf1d9',
	eraser			: '\uf12d',
	// Playback
	prev			: '\uf049',
	next			: '\uf050',
	play			: '\uf04B',
	pause			: '\uf04C',
	stop			: '\uf04D',
	shuffle			: '\uf074',
	// Carets
	up 				: '\uf077',
	down 			: '\uf078',
	// Arrows
	downLongArrow	: '\uf175',
	upLongArrow		: '\uf176',
	leftLongArrow	: '\uf177',
	rightLongArrow	: '\uf178',
	levelDown 		: '\uf149',
	levelUp 		: '\uf148',
	prevCircle 		: '\uf0e2',
	nextCircle 		: '\uf01e',
	exchange		: '\uf0ec',
	downOutline		: '\uf0d7',
	leftOutline		: '\uf0d9',
	// Sort
	sortAlphaAsc	: '\uf15d',
	sortAlphaDes	: '\uf15e',
	sortBarsAsc		: '\uf160',
	sortBarsDes		: '\uf161',
	sortNumAsc		: '\uf162',
	sortNumDes		: '\uf163',
	// Check
	check			: '\uf00c',
	checkCircle		: '\uf058',
	checkCircleAlt	: '\uf05d',
	checkSquare		: '\ud14a',
	checkSquareAlt	: '\uf046',
};