name: Clean workflow runs (automatic)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    # Run daily, at 00:00

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1